### ISSUE TITLE
React v0.14 checklist

### ISSUE THREAD

**Issue by satya164** [scrollback/scrollback#926]
- [x] Chang instances of `React` to `ReactDOM` when necessary
- [x] Add dependency for `ReactDOM`
- [ ] For DOM node refs, directly use the ref, i.e. `this.refs.input` instead of `React.findDOMNode(this.refs.input)` or `this.refs.input.getDOMNode()`
- [x] Remove all occurences of `getDOMNode`
- [ ] Refactor stateless components, e.g. -
```
class MyComponent {
    constructor(props) {
        super(props);
    }

    render() {
        return <div>{this.props.text}</div>;
    }
}
```
Will become,
```
const MyComponent = props => <div>{props.text}</div>;
```
- [ ] Enable compiler optimisations in production with the babel transforms `optimisation.react.inlineElements` and `optimisation.react.constantElements`

**NOTES:**
Most of the process could be automated with <https://github.com/facebook/react/blob/master/packages/react-codemod/README.md>
